// Header file with contents generated by the intrinsic emitter.

namespace llvm::Intrinsic::nvvm {
// def int_nvvm_float_op0 : Intrinsic<[], [llvm_float_ty, llvm_i1_ty,
// llvm_i16_ty]>;
using FloatOp0Modifiers = std::tuple<bool, uint16_t>;
void printOp0Modifiers(raw_ostream &OS, FloatOp0Modifiers Mods);
bool parseOp0Modifiers(StringRef Suffix, FloatOp0Modifiers &Mods);

// def int_nvvm_float_op1 : Intrinsic<[], [llvm_i32_ty, llvm_float_ty]>;
using FloatOp1Modifiers = uint32_t;
void printOp1Modifiers(raw_ostream &OS, FloatOp1Modifiers Mods);
bool parseOp1Modifiers(StringRef Suffix, FloatOp1Modifiers &Mods);

// def int_nvvm_float_op2 : Intrinsic<[], [llvm_i32_ty, llvm_anyfloat_ty]>;
using FloatOp2Modifiers = uint32_t;
void printOp2Modifiers(raw_ostream &OS, FloatOp2Modifiers Mods);
bool parseOp2Modifiers(StringRef Suffix, FloatOp2Modifiers &Mods);

} // namespace llvm::Intrinsic::nvvm
